User.create!(name: 'Admin User', email: 'admin@example.com', password: 'admin')
site = Site.create!(key: 'www.example.com')
Site.create!(key: 'account.example.com')
layout = Layout.create!(name: 'Basic', sections: "header content footer")
Layout.create!(name: 'Minimal', sections: "content")
widget = Widget.create!(title: 'Latest Products', type: 'AssetList')
Page.create!(title: 'Start Page', layout: layout, site: site)
